project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  favicon: figures/next-step.png
  title: "Predictive Movement Ecology"
  page-navigation: true
  
  navbar:
    left:
      - text: Home
        href: index.qmd
      # - case_study.qmd
      # - tutorials.qmd
      - text: Temporal dynamics
        href: exploratory_temporal_dynamics.qmd
      - text: SSF Formulations
        href: ssf_responses.qmd
      - text: Environmental Extrapolation
        href: extrapolation_shape.qmd
      - text: Predictive SSF Walkthrough
        href: predictive_SSF_walkthrough.qmd

    right:
      - icon: github
        href: https://github.com/swforrest/predictive_movement_ecology
        
  # sidebar:
    # - title: "Case Study"
    #   style: floating
    #   contents:
    #     - case_study.qmd
        
    # - title: "Helpful Scripts and Tutorials"
    #   style: floating
    #   contents:
    #     - tutorials.qmd
    #     - exploratory_temporal_dynamics.qmd
    #     - ssf_responses.qmd
    #     - extrapolation_shape.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



