project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  favicon: figures/next-step.png
  title: "Predictive Movement Ecology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - case_study.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



