<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>predictive_ssf_walkthrough_notes – Predictive Movement Ecology</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./figures/next-step.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predictive Movement Ecology</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./exploratory_temporal_dynamics.html"> 
<span class="menu-text">Temporal dynamics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ssf_responses.html"> 
<span class="menu-text">SSF Formulations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./extrapolation_shape.html"> 
<span class="menu-text">Environmental Extrapolation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./predictive_SSF_walkthrough.html"> 
<span class="menu-text">Predictive SSF Walkthrough</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/swforrest/predictive_movement_ecology"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#predictive-ssf-walkthrough-design-notes" id="toc-predictive-ssf-walkthrough-design-notes" class="nav-link active" data-scroll-target="#predictive-ssf-walkthrough-design-notes">Predictive SSF Walkthrough — design notes</a>
  <ul class="collapse">
  <li><a href="#what-the-walkthrough-is-for" id="toc-what-the-walkthrough-is-for" class="nav-link" data-scroll-target="#what-the-walkthrough-is-for">1. What the walkthrough is for</a></li>
  <li><a href="#data-and-covariates" id="toc-data-and-covariates" class="nav-link" data-scroll-target="#data-and-covariates">2. Data and covariates</a>
  <ul class="collapse">
  <li><a href="#measured-baselines-sanity-checks-these-should-reproduce" id="toc-measured-baselines-sanity-checks-these-should-reproduce" class="nav-link" data-scroll-target="#measured-baselines-sanity-checks-these-should-reproduce">Measured baselines (sanity checks — these should reproduce)</a></li>
  <li><a href="#measured-timings" id="toc-measured-timings" class="nav-link" data-scroll-target="#measured-timings">Measured timings</a></li>
  </ul></li>
  <li><a href="#the-parameter-block" id="toc-the-parameter-block" class="nav-link" data-scroll-target="#the-parameter-block">3. The parameter block</a></li>
  <li><a href="#model-formulations" id="toc-model-formulations" class="nav-link" data-scroll-target="#model-formulations">4. Model formulations</a>
  <ul class="collapse">
  <li><a href="#model-a-static-issf" id="toc-model-a-static-issf" class="nav-link" data-scroll-target="#model-a-static-issf">Model A — static iSSF</a></li>
  <li><a href="#model-b-temporally-dynamic-gam" id="toc-model-b-temporally-dynamic-gam" class="nav-link" data-scroll-target="#model-b-temporally-dynamic-gam">Model B — temporally dynamic GAM</a></li>
  <li><a href="#two-things-that-were-checked-not-assumed" id="toc-two-things-that-were-checked-not-assumed" class="nav-link" data-scroll-target="#two-things-that-were-checked-not-assumed">Two things that were checked, not assumed</a></li>
  </ul></li>
  <li><a href="#from-coefficients-to-a-simulator" id="toc-from-coefficients-to-a-simulator" class="nav-link" data-scroll-target="#from-coefficients-to-a-simulator">5. From coefficients to a simulator</a></li>
  <li><a href="#simulation" id="toc-simulation" class="nav-link" data-scroll-target="#simulation">6. Simulation</a>
  <ul class="collapse">
  <li><a href="#two-bugs-found-during-the-first-render" id="toc-two-bugs-found-during-the-first-render" class="nav-link" data-scroll-target="#two-bugs-found-during-the-first-render">Two bugs found during the first render</a></li>
  <li><a href="#starting-locations-start_mode" id="toc-starting-locations-start_mode" class="nav-link" data-scroll-target="#starting-locations-start_mode">Starting locations (<code>start_mode</code>)</a></li>
  <li><a href="#boundary" id="toc-boundary" class="nav-link" data-scroll-target="#boundary">Boundary</a></li>
  </ul></li>
  <li><a href="#aggregation-summaries-validation" id="toc-aggregation-summaries-validation" class="nav-link" data-scroll-target="#aggregation-summaries-validation">7. Aggregation, summaries, validation</a></li>
  <li><a href="#the-amt-route" id="toc-the-amt-route" class="nav-link" data-scroll-target="#the-amt-route">8. The <code>amt</code> route</a></li>
  <li><a href="#provenance" id="toc-provenance" class="nav-link" data-scroll-target="#provenance">9. Provenance</a></li>
  <li><a href="#a.-results-and-how-they-should-be-read" id="toc-a.-results-and-how-they-should-be-read" class="nav-link" data-scroll-target="#a.-results-and-how-they-should-be-read">9a. Results, and how they should be read</a></li>
  <li><a href="#status" id="toc-status" class="nav-link" data-scroll-target="#status">10. Status</a>
  <ul class="collapse">
  <li><a href="#known-limitations-stated-in-the-walkthrough-rather-than-hidden" id="toc-known-limitations-stated-in-the-walkthrough-rather-than-hidden" class="nav-link" data-scroll-target="#known-limitations-stated-in-the-walkthrough-rather-than-hidden">Known limitations, stated in the walkthrough rather than hidden</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">11. References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="predictive-ssf-walkthrough-design-notes" class="level1">
<h1>Predictive SSF Walkthrough — design notes</h1>
<p>Working notes for <code>predictive_SSF_walkthrough.qmd</code>. This file records <em>why</em> the walkthrough is built the way it is — the decisions, the equations, the provenance of each section, and the things that were checked rather than assumed. The <code>.qmd</code> itself is the teaching artefact; this is the record behind it.</p>
<hr>
<section id="what-the-walkthrough-is-for" class="level2">
<h2 class="anchored" data-anchor-id="what-the-walkthrough-is-for">1. What the walkthrough is for</h2>
<p>A simplified, heavily-commented version of the pipeline from <a href="https://github.com/swforrest/dynamic_SSF_sims"><code>swforrest/dynamic_SSF_sims</code></a>, the code accompanying Forrest et al.&nbsp;(2025, <em>Ecography</em>), “Predicting fine-scale distributions and emergent spatiotemporal patterns from temporally dynamic step selection simulations”.</p>
<p>That repo is six scripts. This is one, and it goes:</p>
<pre><code>fit  -&gt;  simulate  -&gt;  aggregate  -&gt;  hourly summaries  -&gt;  assess predictions</code></pre>
<p>The teaching payload is a <strong>contrast between two models</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Model A — static</strong></td>
<td>An ordinary iSSF. One selection coefficient per covariate, constant across the day.</td>
</tr>
<tr class="even">
<td><strong>Model B — temporally dynamic</strong></td>
<td>A GAM where each coefficient is a cyclic smooth function of hour, <code>s(hour, by = x, bs = "cc")</code>.</td>
</tr>
</tbody>
</table>
<p>Both are simulated from, both are aggregated into utilisation distributions, and both are validated against the observed data. The point a reader should leave with: a model whose <em>coefficients</em> look more interesting also has to <em>predict</em> better, and you can check whether it does.</p>
<hr>
</section>
<section id="data-and-covariates" class="level2">
<h2 class="anchored" data-anchor-id="data-and-covariates">2. Data and covariates</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>Individual</td>
<td>Buffalo <strong>2158</strong></td>
</tr>
<tr class="even">
<td>Period</td>
<td><strong>2018-07-25 → 2018-10-31</strong> (2018 dry season)</td>
</tr>
<tr class="odd">
<td>Covariates</td>
<td><strong>NDVI</strong>, <strong>canopy cover</strong>, <strong>slope</strong></td>
</tr>
<tr class="even">
<td>Rasters</td>
<td><code>mapping/ndvi_aug_2018.tif</code>, <code>canopy_cover.tif</code>, <code>slope_raster.tif</code> — all 25 m, EPSG:3112, identical extents</td>
</tr>
</tbody>
</table>
<p><strong>Why a single individual.</strong> Keeps the script readable and fast, and makes validation unambiguous: predicted use is compared against <em>that animal’s</em> observed locations. Extending to multiple individuals is a modelling discussion (pooling, random effects, two-step estimation) that would swamp the pipeline this script is about.</p>
<p><strong>Why the dry-season subset.</strong> Buffalo 2158 is not range-stationary across the full 15 months of data — it shifts roughly 20 km east during 2019. A long-term utilisation distribution validated against the whole track would score badly for reasons that have nothing to do with the model. Restricting to Jul–Oct 2018 keeps the animal in one ~9.5 × 2.5 km band. It also matches the NDVI layer, which is August 2018 only.</p>
<p><strong>Canopy cover is rescaled to 0–1</strong> (<code>canopy_cover / 100</code>), as in the source repo, so its coefficient is on a comparable scale to NDVI’s.</p>
<section id="measured-baselines-sanity-checks-these-should-reproduce" class="level3">
<h3 class="anchored" data-anchor-id="measured-baselines-sanity-checks-these-should-reproduce">Measured baselines (sanity checks — these should reproduce)</h3>
<ul>
<li>2,235 observed locations, ~1 h fix interval</li>
<li>Tentative gamma: <strong>shape 0.4266, scale 786.8</strong></li>
<li>Tentative von Mises: <strong>κ 0.398</strong></li>
<li><code>n_control = 10</code> → 24,563 rows / 2,233 strata; <code>n_control = 25</code> → 58,058 rows / 2,233 strata</li>
<li>Model A corrected movement parameters: <strong>shape 0.4308141, scale 790.3658, κ 0.3924898</strong> (hand-computed and <code>amt::update_sl_distr()</code> agree to 1.7e-9)</li>
<li>Model B hourly parameters stay valid at every hour: shape 0.34–0.81, scale 219–1413, κ −0.39–1.30, mean step length <strong>93 m to 1127 m</strong> across the day</li>
</ul>
</section>
<section id="measured-timings" class="level3">
<h3 class="anchored" data-anchor-id="measured-timings">Measured timings</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model A (<code>fit_issf</code>)</td>
<td>0.4 s</td>
</tr>
<tr class="even">
<td>Model B (<code>cox.ph</code> GAM, 6 smooths, <code>n_control = 25</code>)</td>
<td>~213 s</td>
</tr>
<tr class="odd">
<td>Manual simulation, 5 trajectories × 720 steps</td>
<td>1.5 s (so ~2.5 min per 500-trajectory set)</td>
</tr>
<tr class="even">
<td><code>amt::simulate_path</code>, 10 × 500 steps</td>
<td>~68 s</td>
</tr>
</tbody>
</table>
<p><code>n_control = 25</code> roughly doubles the Model B fit time relative to 10 (94 s → 213 s) but is worth it: the canopy smooth is only marginally significant at 10 (p = 0.17) and clearly significant at 25 (p = 0.017). All six smooths are significant at <code>n_control = 25</code>, with edf 5.4–8.6.</p>
<hr>
</section>
</section>
<section id="the-parameter-block" class="level2">
<h2 class="anchored" data-anchor-id="the-parameter-block">3. The parameter block</h2>
<p>Everything scalable lives in one chunk at the top of the <code>.qmd</code>, so a reader can re-run the whole thing bigger or smaller without hunting through it:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Default</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>which_buffalo</code></td>
<td><code>2158</code></td>
<td>Individual to fit</td>
</tr>
<tr class="even">
<td><code>season_start</code> / <code>season_end</code></td>
<td>2018-07-25 / 2018-11-01</td>
<td>Fitting window</td>
</tr>
<tr class="odd">
<td><code>n_control</code></td>
<td><code>25</code></td>
<td>Available steps per used step</td>
</tr>
<tr class="even">
<td><code>n_traj</code></td>
<td><code>500</code></td>
<td>Simulated trajectories per model</td>
</tr>
<tr class="odd">
<td><code>n_steps</code></td>
<td><code>720</code></td>
<td>Steps per trajectory (720 h = 30 days)</td>
</tr>
<tr class="even">
<td><code>n_ch</code></td>
<td><code>25</code></td>
<td>Candidate steps evaluated at each simulated step</td>
</tr>
<tr class="odd">
<td><code>burn_in</code></td>
<td><code>24</code></td>
<td>Leading steps discarded from each trajectory</td>
</tr>
<tr class="even">
<td><code>start_mode</code></td>
<td><code>"random"</code></td>
<td>Seeding strategy — see §6</td>
</tr>
<tr class="odd">
<td><code>boundary</code></td>
<td><code>"wrapped"</code></td>
<td>Landscape boundary — see §6</td>
</tr>
<tr class="even">
<td><code>ud_res</code></td>
<td><code>100</code> m</td>
<td>Resolution of the all-hours UD</td>
</tr>
<tr class="odd">
<td><code>ud_res_hourly</code></td>
<td><code>250</code> m</td>
<td>Resolution of the 24 hourly UDs (coarser: each holds ~1/24 of the locations)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="model-formulations" class="level2">
<h2 class="anchored" data-anchor-id="model-formulations">4. Model formulations</h2>
<section id="model-a-static-issf" class="level3">
<h3 class="anchored" data-anchor-id="model-a-static-issf">Model A — static iSSF</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>amt<span class="sc">::</span><span class="fu">fit_issf</span>(case_ <span class="sc">~</span> ndvi <span class="sc">+</span> canopy <span class="sc">+</span> slope <span class="sc">+</span> sl_ <span class="sc">+</span> log_sl_ <span class="sc">+</span> cos_ta_ <span class="sc">+</span> <span class="fu">strata</span>(step_id_), ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Also fitted as the equivalent <code>mgcv::gam(cbind(times, step_id_) ~ ..., family = cox.ph)</code> so that both models share one interface for prediction, and so the reader can see the two are the same model.</p>
<p>Movement terms are named <code>sl_</code>, <code>log_sl_</code>, <code>cos_ta_</code> — <strong>amt’s convention, with the trailing underscore</strong>. This matters: <code>amt::update_sl_distr()</code> and <code>update_ta_distr()</code> look for exactly these names, and they’re used in §5 to cross-check the hand-computed movement parameters.</p>
</section>
<section id="model-b-temporally-dynamic-gam" class="level3">
<h3 class="anchored" data-anchor-id="model-b-temporally-dynamic-gam">Model B — temporally dynamic GAM</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mgcv<span class="sc">::</span><span class="fu">gam</span>(<span class="fu">cbind</span>(times, step_id_) <span class="sc">~</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">s</span>(hour, <span class="at">by =</span> ndvi,    <span class="at">bs =</span> <span class="st">"cc"</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">s</span>(hour, <span class="at">by =</span> canopy,  <span class="at">bs =</span> <span class="st">"cc"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">s</span>(hour, <span class="at">by =</span> slope,   <span class="at">bs =</span> <span class="st">"cc"</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">s</span>(hour, <span class="at">by =</span> sl_,     <span class="at">bs =</span> <span class="st">"cc"</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">s</span>(hour, <span class="at">by =</span> log_sl_, <span class="at">bs =</span> <span class="st">"cc"</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">s</span>(hour, <span class="at">by =</span> cos_ta_, <span class="at">bs =</span> <span class="st">"cc"</span>),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">knots =</span> <span class="fu">list</span>(<span class="at">hour =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">24</span>)),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> cox.ph, <span class="at">weight =</span> case_, ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This is a <strong>varying-coefficient model</strong>: <code>s(hour, by = ndvi)</code> fits β_NDVI(hour), a coefficient that is a smooth function of time of day. <code>bs = "cc"</code> (cyclic cubic regression spline) makes the curve join up at midnight. It’s the same idea as the harmonic terms in the paper — β(τ) = α₀ + Σ αⱼ sin(2jπτ/T) + Σ αⱼ₊ₚ cos(2jπτ/T) — with a spline basis instead of a Fourier one, following Klappstein et al.&nbsp;(2024).</p>
<p>Movement terms get the same treatment, which is what lets step length and directional persistence vary across the day in the simulations.</p>
</section>
<section id="two-things-that-were-checked-not-assumed" class="level3">
<h3 class="anchored" data-anchor-id="two-things-that-were-checked-not-assumed">Two things that were checked, not assumed</h3>
<p><strong>(a) Numeric <code>by=</code> smooths are NOT centred — no parametric main effect is needed.</strong></p>
<p>The obvious worry with <code>s(hour, by = ndvi)</code> and no <code>ndvi</code> term alongside it is that mgcv’s sum-to-zero identifiability constraint would force the average of β_NDVI(hour) across the day to be zero, throwing away the overall selection strength. That worry is unfounded: mgcv skips the centring constraint when the <code>by</code> variable is numeric. Checked two ways:</p>
<ul>
<li>Basis dimension. <code>smoothCon(s(hour, by = z, bs = "cc", k = 6))</code> keeps <strong>5</strong> columns after constraints; plain <code>s(hour, bs = "cc", k = 6)</code> keeps <strong>4</strong>. The constraint isn’t applied.</li>
<li>Full fit on this data, with and without a parametric <code>ndvi</code> term: β_NDVI(hour) spans −6.635 → 5.606 <strong>either way</strong>, mean −0.754 either way, edf 8.064 either way. The main effect is redundant and costs ~2 AIC (10553.45 → 10555.44) for the extra parameter.</li>
</ul>
<p>So β_x(τ) is the smooth alone, with nothing added back. The <code>.qmd</code> keeps a short box on this, because it’s a natural thing for a reader to be uneasy about, and the basis-dimension check is a satisfying one-line answer.</p>
<p>In the end the coefficients are extracted with <code>predict()</code> rather than <code>gratia::smooth_estimates()</code>, via a small <code>beta_by_hour()</code> helper. Since neither model has an intercept, predicting the linear predictor at a design where one covariate is 1 and all others are 0 returns that covariate’s coefficient directly. The same call works unchanged on the static model (returning a constant) and the dynamic one (returning the smooth), and <code>se.fit = TRUE</code> gives confidence intervals — so one function serves both models and the downstream code never needs to know which it is holding.</p>
<p><strong>(b) <code>knots = list(hour = c(0, 24))</code> is genuinely needed.</strong></p>
<p>Without it, mgcv places the cyclic endpoints at <code>range(hour)</code> — which is 0 and 23, not 0 and 24:</p>
<pre><code>no knots argument   -&gt;  knots at 0, 4.6, 9.2, 13.8, 18.4, 23
knots = c(0, 24)    -&gt;  knots at 0, 4.8, 9.6, 14.4, 19.2, 24</code></pre>
<p>The first wraps hour 23 onto hour 0 and squeezes an hour out of the daily cycle. Small, but real. The same two-line fix has been applied to the temporal GAMs in <code>ssf_responses.qmd</code>.</p>
<hr>
</section>
</section>
<section id="from-coefficients-to-a-simulator" class="level2">
<h2 class="anchored" data-anchor-id="from-coefficients-to-a-simulator">5. From coefficients to a simulator</h2>
<p>Both models are reduced to the <strong>same object</strong>: a 24-row table with columns <code>hour, ndvi, canopy, slope, shape, scale, kappa</code>. Model A’s is flat; Model B’s cycles. Everything downstream is model-agnostic, which is the whole reason the source repo used this format (<code>TwoStep_2pDaily_coefs_dry_*.csv</code>).</p>
<p>Habitat coefficients come from the fitted model. Movement parameters use the iSSF update rules (Avgar et al.&nbsp;2016; Fieberg et al.&nbsp;2021) — the tentative distributions fitted to the observed steps are <em>corrected</em> by the fitted movement coefficients:</p>
<pre><code>shape(τ) = shape_tentative + β_log_sl_(τ)
scale(τ) = 1 / ( 1/scale_tentative − β_sl_(τ) )
kappa(τ) = kappa_tentative + β_cos_ta_(τ)</code></pre>
<p>For Model A these are checked against <code>amt::update_sl_distr()</code> / <code>update_ta_distr()</code>, which implement exactly this. That cross-check is the highest-value assertion in the script: if the update rules are wrong, every simulated step length is wrong and nothing downstream means anything.</p>
<p><strong>Habitat selection surfaces</strong> are then precomputed once per hour, on the log scale:</p>
<pre><code>log w(x, τ) = β_ndvi(τ)·NDVI(x) + β_canopy(τ)·canopy(x) + β_slope(τ)·slope(x)</code></pre>
<p>giving a 24-layer raster stack per model. The simulator indexes into it by hour rather than re-evaluating the linear predictor at every candidate step.</p>
<hr>
</section>
<section id="simulation" class="level2">
<h2 class="anchored" data-anchor-id="simulation">6. Simulation</h2>
<p>The sampler is the redistribution kernel written out longhand: <strong>movement kernel × habitat kernel</strong>. At each step, draw <code>n_ch</code> candidate step lengths from <code>rgamma(shape(τ), scale(τ))</code> and turning angles from a von Mises with κ(τ), project the candidate endpoints, look up <code>log w</code> in the hour-τ layer, and choose one with <code>sample(n_ch, 1, prob = exp(log_w))</code>.</p>
<p>Two performance decisions, both of which matter because the loop runs ~360,000 times per 500-trajectory set:</p>
<ul>
<li><strong>All random numbers are drawn up front</strong>, not inside the loop.</li>
<li><strong>Raster lookup avoids <code>terra::extract()</code>.</strong> The stack is digested once into a plain matrix via <code>terra::values()</code> (one row per cell, row-major, one column per layer), and lookups are done with cell arithmetic: <code>col = floor((x - xmin)/resx) + 1</code>, <code>row = floor((ymax - y)/resy) + 1</code>, <code>cell = (row - 1) * ncol + col</code>. Verified against <code>terra::extract()</code> on 1,000 random points (max absolute difference 0, NA handling identical) and against <code>cellFromXY()</code>. This is what brings a 500 × 720-step run down to ~2.5 minutes.</li>
</ul>
<p>The source repo calls <code>terra::extract()</code> inside the loop; on the scale it was run at (an HPC cluster) that was fine, but it is the main reason a naive port feels slow on a laptop.</p>
<section id="two-bugs-found-during-the-first-render" class="level3">
<h3 class="anchored" data-anchor-id="two-bugs-found-during-the-first-render">Two bugs found during the first render</h3>
<p><strong>1. Turning angles were misaligned with hours (real correctness bug).</strong></p>
<p>The first version built the von Mises inputs per <em>candidate</em>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>kappa_vec <span class="ot">&lt;-</span> <span class="fu">rep</span>(coefs<span class="sc">$</span>kappa[step_hours], <span class="at">each =</span> n_ch)   <span class="co"># length n_steps * n_ch</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ta <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">mapply</span>(Rfast<span class="sc">::</span>rvonmises, <span class="at">n =</span> n_ch, <span class="at">m =</span> mu_vec, <span class="at">k =</span> <span class="fu">abs</span>(kappa_vec))) <span class="sc">-</span> pi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>mapply</code> then made <code>n_steps * n_ch</code> calls, each returning <code>n_ch</code> draws — 450,000 values instead of 18,000, and block <em>i</em> of the result came from <code>kappa[step_hours[ceiling(i / n_ch)]]</code> rather than <code>kappa[step_hours[i]]</code>. Step 2 was getting hour 1’s concentration, step 30 hour 2’s, and so on. The fix is to pass a per-<em>step</em> vector, so <code>mapply</code> makes one call per step:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>kappa_step <span class="ot">&lt;-</span> coefs<span class="sc">$</span>kappa[step_hours]                    <span class="co"># length n_steps</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ta <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">mapply</span>(Rfast<span class="sc">::</span>rvonmises, <span class="at">n =</span> n_ch, <span class="at">m =</span> mu_step, <span class="at">k =</span> <span class="fu">abs</span>(kappa_step))) <span class="sc">-</span> pi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This is silent — no error, just wrong turning angles — so it is the more dangerous of the two.</p>
<p><strong>2. <code>lookup()</code> crashed on a non-finite coordinate — root cause: <code>Rfast::rvonmises</code>.</strong></p>
<p><code>inside &lt;- col &gt;= 1 &amp; col &lt;= ncol &amp; ...</code> evaluates to <code>NA</code> (not <code>FALSE</code>) when the coordinate is <code>NaN</code>, and <code>NA</code> is not permitted as a subscript in <code>out[inside] &lt;- ...</code>. This aborted the first render at trajectory 53. Guarded with an explicit <code>!is.na(col) &amp; !is.na(row) &amp; ...</code>, which is the correct semantics anyway: a non-finite coordinate is not inside the raster, so it gets the same negligible weight as one that falls outside.</p>
<p>Tracked the <code>NaN</code> to its source by running trajectories until one failed and inspecting the state: the failing step had exactly one non-finite <strong>turning angle</strong>, with all step lengths finite. Two problems with <code>Rfast::rvonmises()</code>, both confirmed directly:</p>
<ul>
<li><strong>It occasionally returns <code>NaN</code></strong> — 6 non-finite in 4.8 × 10⁷ draws (~1 in 8 million), at small positive concentrations (κ ≈ 0.16, 0.25). Negligible-sounding, but a production run makes <code>n_traj × n_steps × n_ch</code> ≈ 9 million draws <em>per model</em>, so roughly one per run. That is exactly why it killed one render and then resisted reproduction across 6,000 trajectories.</li>
<li><strong>It ignores <code>set.seed()</code>.</strong> <code>Rfast</code> uses its own RNG: two calls under the same seed return different values. The simulations were therefore never reproducible, seed at the top or not.</li>
</ul>
<p>The second problem is the more serious one for a teaching script, and it is inherited straight from the source repo. <strong>Switched to <code>circular::rvonmises()</code></strong>, which is reproducible under <code>set.seed()</code>, produced zero non-finite values in 4.8 × 10⁷ draws with the same parameters, and is marginally faster. Drawing is now done once per <em>hour</em> (24 calls) rather than once per step, scattering into position with <code>outer()</code> — verified for length, hour alignment (correlation between mean |turning angle| and κ across hours = −0.994) and reproducibility.</p>
<p><code>circular</code> is called with <code>::</code> rather than attached, because attaching it masks <code>stats::sd</code> and <code>stats::var</code>.</p>
<p>A related, harmless edge case in the wrapped boundary: <code>y %% y_extent</code> can return exactly 0, which maps to <code>row = nrow + 1</code> and is therefore treated as outside. Measure-zero and non-fatal, so left as is.</p>
</section>
<section id="starting-locations-start_mode" class="level3">
<h3 class="anchored" data-anchor-id="starting-locations-start_mode">Starting locations (<code>start_mode</code>)</h3>
<p>Three strategies, because they answer different questions:</p>
<ul>
<li><strong><code>"observed"</code></strong> — every trajectory starts at the animal’s first observed location. Asks <em>where would this animal have gone from where it actually was?</em> The spread that emerges is home-range-like. The right choice for short simulations, and the one to use if the question is about space use rather than landscape-scale distribution.</li>
<li><strong><code>"observed_sample"</code></strong> — starts drawn at random from the observed locations. Seeded in habitat the animal actually used, but not all from one point, so the resulting UD isn’t dominated by a single origin.</li>
<li><strong><code>"random"</code></strong> — uniform across the raster extent. Asks <em>what is the stationary distribution of this movement process over this landscape?</em> This is what the long-term UD and the validation need, and what the source repo used.</li>
</ul>
</section>
<section id="boundary" class="level3">
<h3 class="anchored" data-anchor-id="boundary">Boundary</h3>
<ul>
<li><strong><code>"wrapped"</code></strong> (toroidal, via <code>%%</code>) — no edge effects, so the process has a well-defined stationary distribution. Used for everything quantitative. Requires the raster origin at (0,0), restored afterwards.</li>
<li><strong><code>"reflective"</code></strong> — candidate steps outside the extent get near-zero weight. Used only for the illustrative trajectory plot, because paths don’t jump across the frame.</li>
</ul>
<p>Burn-in interacts with both: seeding from a single observed point needs a real burn-in before the trajectory forgets where it started; seeding uniformly at random needs much less.</p>
<hr>
</section>
</section>
<section id="aggregation-summaries-validation" class="level2">
<h2 class="anchored" data-anchor-id="aggregation-summaries-validation">7. Aggregation, summaries, validation</h2>
<ul>
<li><strong>Aggregation</strong> — <code>terra::rasterize(coords, template, fun = "sum")</code>, all-hours at 100 m and per hour at 250 m, normalised to sum to 1 so the two models are comparable. Plus a convergence check built from subsets of the already-simulated trajectories (25/50/100/250/500), correlated against the full result — this is how a reader decides whether <code>n_traj</code> was enough for <em>their</em> system.</li>
<li><strong>Hourly summaries</strong> — hourly means of step length and each covariate, simulated vs observed. With one individual there’s no between-animal spread to plot, so the observed track is split into weekly blocks to give a comparable distribution of observed hourly curves.</li>
<li><strong>Validation</strong> — continuous Boyce index (<code>ecospat::ecospat.boyce</code>), Spearman and Pearson, overall and separately for each of the 24 hours. The hourly panel is the miniature version of the key result in Forrest et al.&nbsp;(2025).</li>
</ul>
<hr>
</section>
<section id="the-amt-route" class="level2">
<h2 class="anchored" data-anchor-id="the-amt-route">8. The <code>amt</code> route</h2>
<p>Near the end, the same thing done with the package: <code>amt::redistribution_kernel()</code> + <code>simulate_path()</code> (Signer et al.&nbsp;2023), shown for Model A.</p>
<p><strong>Two things that are needed to make this work</strong>, neither of them obvious from the resulting error messages:</p>
<ol type="1">
<li>The default extraction function uses <code>where = "both"</code>, producing columns named <code>ndvi_start</code> and <code>ndvi_end</code>. A model referring to plain <code>ndvi</code> then fails with <code>object 'ndvi' not found</code>. A custom <code>fun</code> with <code>where = "end"</code> fixes it — but must <em>also</em> compute <code>log_sl_</code> and <code>cos_ta_</code>, since the kernel supplies only <code>sl_</code> and <code>ta_</code> (otherwise the next error is <code>object 'log_sl_' not found</code>).</li>
<li>The kernel has no toroidal option and terminates a path once too many proposed steps fall outside the map. On the 14 × 14 km simulation crop, paths stop after ~150 of 500 steps. The walkthrough therefore hands <code>amt</code> the <em>full</em> covariate rasters, and uses the opportunity to point out that this is exactly the edge effect the wrapped boundary in our own sampler avoids.</li>
</ol>
<p>The deeper limitation, and why the manual sampler exists here: the kernel is built from one fitted model against a fixed <code>map</code>, so coefficients that change with hour need either a custom extraction function that indexes the hour-τ layer by the point’s timestamp — at the cost of a per-row <code>terra::extract()</code>, precisely the overhead the matrix lookup was written to avoid — or a kernel rebuilt per hour.</p>
<hr>
</section>
<section id="provenance" class="level2">
<h2 class="anchored" data-anchor-id="provenance">9. Provenance</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Walkthrough section</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Steps, random steps, model fitting</td>
<td><code>DynamicSSF_1_Step_generation.qmd</code>, <code>DynamicSSF_2a_Model_fit_dry_season.qmd</code></td>
</tr>
<tr class="even">
<td>Hourly coefficients, RSF surfaces, <code>simulate_ssf()</code></td>
<td><code>DynamicSSF_3_Simulating_trajectories.qmd</code></td>
</tr>
<tr class="odd">
<td>Rasterising simulated locations</td>
<td><code>DynamicSSF_4a_Aggregating_simulations.R</code></td>
</tr>
<tr class="even">
<td>Convergence check</td>
<td><code>DynamicSSF_4b_Simulation_convergence.R</code></td>
</tr>
<tr class="odd">
<td>Hourly summary statistics and plots</td>
<td><code>DynamicSSF_5_Hourly_summaries.qmd</code></td>
</tr>
<tr class="even">
<td>Boyce index, hourly validation</td>
<td><code>DynamicSSF_6_Assessing_predictions.qmd</code></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="a.-results-and-how-they-should-be-read" class="level2">
<h2 class="anchored" data-anchor-id="a.-results-and-how-they-should-be-read">9a. Results, and how they should be read</h2>
<p>The first complete render produced a more interesting outcome than expected, and the walkthrough text was rewritten to report it honestly rather than to tell the tidy story.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Static</th>
<th>Dynamic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AIC</td>
<td>14523.35 (edf 6)</td>
<td><strong>13311.24</strong> (edf 43.1), ΔAIC 1212</td>
</tr>
<tr class="even">
<td>Boyce index, whole-day UD</td>
<td><strong>0.729</strong></td>
<td>0.692</td>
</tr>
<tr class="odd">
<td>Spearman vs observed KDE</td>
<td>0.025</td>
<td><strong>0.223</strong></td>
</tr>
<tr class="even">
<td>Boyce index, mean across 24 hours</td>
<td>0.275</td>
<td><strong>0.529</strong> (better in 21 of 24 hours)</td>
</tr>
</tbody>
</table>
<p>So the dynamic model wins decisively on fit, on the KDE comparison and on the hourly validation — but is <em>marginally worse</em> on the single whole-day Boyce index. That is not a contradiction: the whole-day UD pools every hour, which averages away exactly the advantage the dynamic model has. The two models put the animal in much the same places over 30 days and disagree about the schedule; a pooled metric cannot see a schedule.</p>
<p>This is now the walkthrough’s closing point — the validation has to match the claim being made, and a better-fitting model has not automatically earned the claim that it predicts better.</p>
<p><strong>The convergence check fails, and that is left visible on purpose.</strong> Spearman correlation against the full 500-trajectory UD runs 0.26 / 0.36 / 0.46 / 0.62 / 0.86 / 1.00 at 10 / 25 / 50 / 100 / 250 / 500 trajectories — still climbing steeply, nowhere near flat. An earlier draft of the prose claimed the curve “flattens well before the full set”; that was wrong and was corrected. The diagnostic now runs at two aggregation resolutions to show the second lever (coarser cells converge much faster on the same simulations), and a callout states plainly that the results are an illustration of the method rather than a settled statement about this animal.</p>
</section>
<section id="status" class="level2">
<h2 class="anchored" data-anchor-id="status">10. Status</h2>
<ul class="task-list">
<li><label><input type="checkbox" checked="">Design decisions settled and verified against the data</label></li>
<li><label><input type="checkbox" checked=""><code>by=</code> centring question resolved empirically</label></li>
<li><label><input type="checkbox" checked=""><code>knots</code> issue confirmed and fixed in <code>ssf_responses.qmd</code></label></li>
<li><label><input type="checkbox" checked=""><code>predictive_SSF_walkthrough.qmd</code> written</label></li>
<li><label><input type="checkbox" checked="">Model fitting timings confirmed acceptable for rendering (~3.5 min for Model B)</label></li>
<li><label><input type="checkbox" checked="">Simulations run at full scale (500 x 720, three sets, ~2.5 min each)</label></li>
<li><label><input type="checkbox" checked="">Gifs generated (hourly selection surfaces; hourly UDs)</label></li>
<li><label><input type="checkbox" checked="">Turning-angle alignment bug found and fixed</label></li>
<li><label><input type="checkbox" checked=""><code>Rfast::rvonmises</code> NaN + non-reproducibility diagnosed; switched to <code>circular::rvonmises</code></label></li>
<li><label><input type="checkbox" checked="">Validation results checked, and prose corrected where it contradicted them</label></li>
<li><label><input type="checkbox">Final render with the <code>circular::rvonmises</code> switch (in progress)</label></li>
<li><label><input type="checkbox">Whole-site render with the new navbar entry</label></li>
</ul>
<section id="known-limitations-stated-in-the-walkthrough-rather-than-hidden" class="level3">
<h3 class="anchored" data-anchor-id="known-limitations-stated-in-the-walkthrough-rather-than-hidden">Known limitations, stated in the walkthrough rather than hidden</h3>
<ul>
<li>The utilisation distributions have <strong>not converged</strong> at 500 trajectories.</li>
<li>Fitted to a single individual over a single season, so nothing here generalises to the population; there is no random-effects or two-step estimation.</li>
<li>NDVI is a single August 2018 layer held fixed, while the fitting window spans late July to October.</li>
<li>The Boyce index validates against the same animal’s observed locations — in-sample in the sense that the model was fitted to those same locations. A genuine out-of-sample test would hold out a period or an individual.</li>
</ul>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">11. References</h2>
<ul>
<li>Forrest, S.W. et al.&nbsp;(2025) <em>Ecography</em> 2025(2). doi:10.1111/ecog.07421</li>
<li>Signer, J. et al.&nbsp;(2023) <em>Methods Ecol Evol</em>. Simulating animal space use from fitted iSSFs.</li>
<li>Klappstein, N.J. et al.&nbsp;(2024) <em>Methods Ecol Evol</em>. Step selection functions with non-linear and random effects.</li>
<li>Avgar, T. et al.&nbsp;(2016) <em>Methods Ecol Evol</em>. Integrated step selection analysis.</li>
<li>Fieberg, J. et al.&nbsp;(2021) <em>J Anim Ecol</em>. A ‘How to’ guide for interpreting parameters in habitat-selection analyses.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>